
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "QuestionAlreadyExist", targetNamespace = "http://businessLogic/")
public class QuestionAlreadyExist_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QuestionAlreadyExist faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public QuestionAlreadyExist_Exception(String message, QuestionAlreadyExist faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public QuestionAlreadyExist_Exception(String message, QuestionAlreadyExist faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.QuestionAlreadyExist
     */
    public QuestionAlreadyExist getFaultInfo() {
        return faultInfo;
    }

}
